type: order_cards
visible: false
header: Matrix Product
text: >
  Reorder the matrix product operations in the optimal

  order:


  $$A_{5 \times 10} \  B_{10 \times 2}\ C_{2 \times 30}\ D_{30 \times 3}\ E_{3
  \times 9}$$
shuffle: true
score: 1
quiz:
  variants:
    - text: $DE$
    - text: $CD$
    - text: $BC$
    - text: $AB$
answer:
  - 719b6a822a9e8356d7da34c640830ccc
  - 2d04fd9f784e178deef129ffb9352859
  - ec99904cdb33045352bce063410da1a4
  - b390fad1e5dd310b52f7d08ade8290ea
