type: choose_any
visible: false
text: Select the correct statements
header: Matrix Product Quiz
shuffle: true
score: 1
quiz:
  variants:
    - text: |
        $\forall A \in \mathbb R^{N \times N}$ and 
        $\forall \mathbf x \in \mathbb R^M \Rightarrow 
        A \mathbf x \in \mathbb R^N$ 
    - text: |
        $\forall A \in \mathbb R^{N \times N}$ and 
        $\forall \mathbf x \in \mathbb R^N \Rightarrow 
        A \mathbf x \in \mathbb R^N$ 
    - text: |
        $\forall A \in \mathbb R^{N \times K}$ and 
        $\forall B \in \mathbb R^{K \times M} \Rightarrow 
        A B \in \mathbb R^{N \times M}$ 
    - text: |
        $\forall A \in \mathbb R^{N \times N}$ and 
        $\forall B \in \mathbb R^{K \times M} \Rightarrow 
        A B \in \mathbb R^{N \times M}$ 
    - text: >
        $\forall A = \begin{bmatrix}
          \mathbf a_1 & 
          \dots &
          \mathbf a_N
        \end{bmatrix} \in \mathbb R^{K \times N}$ 


        and


        $\forall B = \begin{bmatrix}
          \mathbf b_1 & \dots & \mathbf b_M
        \end{bmatrix} \in \mathbb R^{K \times M} \Rightarrow$


        $A^T B = \begin{bmatrix}
          \left<\mathbf a_1, \mathbf b_1\right> & \dots & \left<\mathbf a_1, \mathbf b_M\right> \\
          \vdots & \ddots & \vdots \\
          \left<\mathbf a_N, \mathbf b_1\right> & \dots & \left<\mathbf a_N, \mathbf b_M\right>
        \end{bmatrix} \in \mathbb R^{N \times M}$
    - text: |
        $\forall A \in \mathbb R^{K \times N}$ and
        $\forall B = \begin{bmatrix}
          \mathbf b_1 & \dots & \mathbf b_M
        \end{bmatrix} \in \mathbb R^{K \times M} \Rightarrow$
        $A^T B = \begin{bmatrix}
          A^T \mathbf b_1 & \dots & A^T \mathbf b_M
        \end{bmatrix} \in \mathbb R^{N \times M}$
    - text: |
        $\forall B \in \mathbb R^{K \times N}$ and
        $\forall A = \begin{bmatrix}
          \mathbf a_1 & \dots & \mathbf a_N
        \end{bmatrix} \in \mathbb R^{K \times M} \Rightarrow$
        $A^T B = \begin{bmatrix}
          \mathbf a_1^T B \\ \vdots \\ \mathbf a_N^T B
        \end{bmatrix} \in \mathbb R^{N \times M}$
    - text: |
        Suppose that we want to calculate the product $A B$ and we realise
        that matrix $A$ contains zeros in $50\%$ of the positions. That
        means that we can perform $50\%$ less operations of multiplication to
        calculate $AB$
    - text: |
        Suppose that we want to calculate the product $A B$ and we realise
        that both matrices $A$ and $B$ contains zeros in $50\%$ of the 
        positions. That
        means that we can perform $75\%$ less operations of multiplication to
        calculate $AB$
    - text: |
        Matrix product $AB$ is always equal to elementwise matrix
        product $A \cdot B$
    - text: >
        $\forall \alpha, \beta \in \mathbb R$, $\forall \mathbf x \in \mathbb
        R^M$ and 

        $\forall A, B \in \mathbb R^{N \times M} \Rightarrow$

        $(\alpha A + \beta B ) \mathbf x = \alpha A \mathbf x + \beta B \mathbf
        x$
    - text: >
        $\forall \alpha, \beta \in \mathbb R$, 

        $\forall \mathbf x, \mathbf y \in \mathbb R^M$ and 

        $\forall A \in \mathbb R^{N \times M} \Rightarrow$

        $A (\alpha \mathbf x + \beta \mathbf y)  = \alpha A \mathbf x + \beta A
        \mathbf y$
answer:
  - 5ed8959b64c4290a4463308f5056597f
  - 8c287084714b7d05b3b6d62de91050de
  - f5a436ed06bc37fd8c355c30c503a5de
  - 75968153bcd6358a07d39a415d6f37a1
  - a03219204f4723d744198095de967ac4
  - 7ae85ffebbdaf84d9d01a4b6fab18a5d
  - bc872d37e7a34e654affe7414c2a30da
  - 31361d57c839ab349686ecb51f57b83b
  - 923b5a486f22ca9bbd264fe5c072c863
  - 8be0a6b8d893020888957febefc726c5
  - 361ace32be5fabc0f992e9cac0f53d75
  - cbd9e0abc1048a1817d297815cb946f8
